name = "ras-os"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[[durable_objects.bindings]]
name = "USER_STORE"
class_name = "UserStore"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["UserStore"]
