name: GitHub Pages Deploy

on:
  push:
    branches:
      - main-react

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
      - run: npm install
      - run: npm run build
      
      - name: Deploy
      - run: npm run deploy
